### ISSUE TITLE
Use Google Analytics

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#158]
@sb2nov Would this be of interest? You would have access to the stats since you're the owner. If you are interested there's [this Gitbook plugin](https://plugins.gitbook.com/plugin/analytics) we can use.

**Comment by sb2nov** [comment]
Looks great, I can try setting it up sometime

**Comment by simeg** [comment]
It would be interesting to see how many visitors each month the guide gets

**Comment by sb2nov** [comment]
Yes, updated the label and will try to get it out soon.

**Comment by simeg** [comment]
Done. Great!

**Comment by simeg** [comment]
@sb2nov It's now been 5 weeks since you enable the Google Analytics plugin, would you mind sharing any statistics on the guide? :) Would be super interesting.

**Comment by sb2nov** [comment]
Sorry there was an issue with the setup which I just fixed in https://github.com/sb2nov/mac-setup/commit/5810d849f0c8e4fec5ed52035588e9380c81c718

I did look at google keywords to gain some other insights:
1. `ZSH` search is the most popular and is used by a few thousand ppl every month.
2. Next it is followed by scala, vagrant, homebrew, virtualenv and variants of these.
3. A large number of backlinks to the site are from Github / Stackoverflow & Twitter. There are also some university pages too which was exciting.

**Comment by Kyslik** [comment]
This is perfect :)

**Comment by simeg** [comment]
@sb2nov Would it be possible to add us as collaborators to the Google Analytics project? No need for any edit rights. [I found this article on how to do it](https://support.google.com/analytics/answer/1009702?hl=en).

Would be awesome to get the same transparency as you have.

**Comment by sb2nov** [comment]
Thanks, this is perfect. I'm traveling right now but can take a look at this as soon as I get back.

**Comment by sb2nov** [comment]
@simeg I have added you to the Google Analytics. @Kyslik your email is private on Github so can add you if you could send me an email address on `firstname @ FirstnameLastName.com`
