### ISSUE TITLE
Add useful docker commands

### ISSUE THREAD

**Issue by simeg** [sb2nov/mac-setup#172]
### I'm Submitting a ...

```
[ ] Bug report
[x] Tool/language/etc documentation request
```

### Tool/Language/etc
I use `docker` a lot in my day-to-day work and I very often learn about new commands from my colleagues and I constantly find myself surprised about what command are available. I'm thinking about commands like `log`, `inspect`, `top` etc. It would be nice with a curated list of useful commands.

**Comment by Kyslik** [comment]
This is going to be a big list, maybe better would be just suggest some youtube guide that explains it all?

For example I visit this gist a lot https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430

**Comment by simeg** [comment]
We don't have to cover everything, but like the most 5-10 useful commands. How to clean away your unused resources could be one of the commands.

**Comment by sb2nov** [comment]
Build, run, pull etc just sound enough for most ppl I think.

**Comment by simeg** [comment]
Yeah, we could start with the essential stuff but what I also want to include are the useful but not so essential commands. But yes, let's start with the essentials.

**Comment by simeg** [comment]
And hey look at that, finally I have a face for your nickname @sb2nov :)

**Comment by sb2nov** [comment]
Haha :)

**Comment by Kyslik** [comment]
What about just recommending another repo where they are focusing on the Docker itself?

https://github.com/wsargent/docker-cheat-sheet

**Comment by simeg** [comment]
@Kyslik What is the purpose of this repo if we only will be linking to other resources? Sure, it's handy to not do any work but just refer to someone else's work but not sure what real value that gives. I think we should keep as much information here as possible, even if it means we have to write it ourselves. I'm sorry, but I refuse to link to another repo just because it's convenient.

I've started writing this section and I'll hopefully have it done in a few weeks.

Happy holidays! ☃️🎄🎅❄️ 🎁

**Comment by hugovk** [comment]
> What is the purpose of this repo if we only will be linking to other resources?

> This guide covers the basics of setting up a development environment on a new Mac. Whether you are an experienced programmer or not, this guide is intended for everyone to use as a reference for setting up your environment or installing a languages/libraries.

I vote for including the basics and linking to a more thorough guide.

**Comment by Kyslik** [comment]
Yea, the installation guide (not just docker but docker-compose as well and docker related tools like completition for zsh) should be here. And also we should mention the “tricks” (good to knows) in order to run the docker on Mac (volumes, permissions)...

The guide - repo, I linked above is already curated by large community and has 10k stars.

Martin Kiesel

**Comment by Kyslik** [comment]
(deleted my email message, since it does not support md, sorry for spam)

Yea, the installation guide (not just `docker` but `docker-compose` as well and docker related tools like completition for `zsh`) should be here. And also we should mention the "tricks" (good to knows) in order to run the docker on Mac (volumes, permissions)...

The guide - repo, I linked above is already curated by large community and has 10k stars.

You too have great holidays 🏂 ⛄️

**Comment by simeg** [comment]
I consider this project to be more than just how to install stuff, but yes that is what's being said in the guide. I see it as sort of "here's how to install it and here's some basic information that could be useful"-guide. I didn't mean we should include everything here, just that we should cover basic useful stuff and some "tips n' trix". 

Sorry for any misunderstanding from my part. What I'm writing is not covering every command, only the most useful ones. I'll link to the popular guide under a "Learn more" section or simliar!
