### ISSUE TITLE
no references to python3 + probably best to install python packages via pip

### ISSUE THREAD

**Issue by myyc** [sb2nov/mac-setup#75]
Hi, very nice guide. I work full time as a data person with Python3 + data stack (pandas, etc.) on Mac OSX and it's pretty stable, also it's probably recommended to default to Py3k and mention Python 2.7 as an "if all else fails" alternative.

Also, it's probably a better idea to install things via `pip` rather than `brew` since that way you skip the extra layer – plus there might be useful libraries that aren't available via Homebrew so you're stuck with `pip` anyway.

What do you think?

**Comment by sb2nov** [comment]
@myyc I think that'll be a great. I'm actually thinking of working on a docker guide and then creating a set of useful environments there.

**Comment by rowmatrix** [comment]
@sb2nov @myyc This could solved using pyenv (similar to rbenv) https://github.com/yyuu/pyenv
You could install anaconda3 and anaconda2 in the same directory. Use anaconda3 as your primary python version and anaconda2 as a fail-safe. This way you don't need to install so many packages with brew or pip. I mention anaconda since you're doing data analysis, but you could also do python3 and python2 instead. 

I can submit a PR that mentions pyenv as an alternative way to install Python.  Personally, it's been a lifesaver for me!

**Comment by sb2nov** [comment]
@rowmatrix that would be great, it'll be great to see a PR about this :)
